In [1]:
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])


In [3]:
x= torch.rand(5,3)
print(x)

tensor([[0.9249, 0.1475, 0.6625],
        [0.1973, 0.9945, 0.0998],
        [0.8400, 0.7499, 0.9531],
        [0.3755, 0.4482, 0.4573],
        [0.7529, 0.7728, 0.2527]])


In [4]:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.9834, -1.5998, -0.7128],
        [-0.8984,  1.5838,  0.2564],
        [ 0.9020, -2.0404,  0.1239],
        [ 0.5063, -0.9141, -0.2745],
        [-0.5229, -0.2646,  0.4945]])


In [9]:
print(x.size())

torch.Size([5, 3])


In [10]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)


In [11]:
lstm = nn.LSTM(3, 3)  # Input dim is 3, output dim is 3
inputs = [torch.randn(1, 3) for _ in range(5)]  # make a sequence of length 5

# initialize the hidden state.
hidden = (torch.randn(1, 1, 3),
          torch.randn(1, 1, 3))
for i in inputs:
    # Step through the sequence one element at a time.
    # after each step, hidden contains the hidden state.
    out, hidden = lstm(i.view(1, 1, -1), hidden)

# alternatively, we can do the entire sequence all at once.
# the first value returned by LSTM is all of the hidden states throughout
# the sequence. the second is just the most recent hidden state
# (compare the last slice of "out" with "hidden" below, they are the same)
# The reason for this is that:
# "out" will give you access to all hidden states in the sequence
# "hidden" will allow you to continue the sequence and backpropagate,
# by passing it as an argument  to the lstm at a later time
# Add the extra 2nd dimension
inputs = torch.cat(inputs).view(len(inputs), 1, -1)
hidden = (torch.randn(1, 1, 3), torch.randn(1, 1, 3))  # clean out hidden state
out, hidden = lstm(inputs, hidden)
print(out)
print(hidden)


tensor([[[-0.0187,  0.1713, -0.2944]],

        [[-0.3521,  0.1026, -0.2971]],

        [[-0.3191,  0.0781, -0.1957]],

        [[-0.1634,  0.0941, -0.1637]],

        [[-0.3368,  0.0959, -0.0538]]], grad_fn=<CatBackward>)
(tensor([[[-0.3368,  0.0959, -0.0538]]], grad_fn=<ViewBackward>), tensor([[[-0.9825,  0.4715, -0.0633]]], grad_fn=<ViewBackward>))


In [7]:
print(x.size())

torch.Size([5, 3])


In [8]:
y = torch.rand(5,3)

In [9]:
y

tensor([[0.3153, 0.0920, 0.0727],
        [0.3490, 0.2120, 0.1176],
        [0.2401, 0.7996, 0.6852],
        [0.2529, 0.0630, 0.2193],
        [0.3296, 0.2671, 0.1626]])

In [10]:
print(x+y)

tensor([[ 2.2987, -1.5078, -0.6401],
        [-0.5494,  1.7958,  0.3740],
        [ 1.1422, -1.2408,  0.8092],
        [ 0.7592, -0.8510, -0.0552],
        [-0.1933,  0.0024,  0.6571]])


In [11]:
print(torch.add(x,y))

tensor([[ 2.2987, -1.5078, -0.6401],
        [-0.5494,  1.7958,  0.3740],
        [ 1.1422, -1.2408,  0.8092],
        [ 0.7592, -0.8510, -0.0552],
        [-0.1933,  0.0024,  0.6571]])


In [12]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[ 2.2987, -1.5078, -0.6401],
        [-0.5494,  1.7958,  0.3740],
        [ 1.1422, -1.2408,  0.8092],
        [ 0.7592, -0.8510, -0.0552],
        [-0.1933,  0.0024,  0.6571]])


In [13]:
y.add(x)

tensor([[ 2.2987, -1.5078, -0.6401],
        [-0.5494,  1.7958,  0.3740],
        [ 1.1422, -1.2408,  0.8092],
        [ 0.7592, -0.8510, -0.0552],
        [-0.1933,  0.0024,  0.6571]])

In [14]:
print(x[:,1])

tensor([-1.5998,  1.5838, -2.0404, -0.9141, -0.2646])


In [17]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8) # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())
# If you want to resize/reshape tensor, you can use torch.view

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [18]:
# If you have a one element tensor, use .item() to get the value as a Python number
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.4746])
-0.47461026906967163


In [19]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [20]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [21]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [22]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [25]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
else:
    print("cuda is not available")

cuda is not available


In [26]:
x = torch.ones(2,2, requires_grad = True)

In [27]:
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [28]:
y = x+2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


In [29]:
print(y.grad_fn)

In [30]:
z = y*y*3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)


In [31]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)


False
True


In [32]:
out.backward()

In [34]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [35]:
x = torch.randn(3, requires_grad=True)
y = x * 2
while y.data.norm() < 1000:
    y = y * 2
print(y)

tensor([ 956.5819, 1293.7478,  596.5690], grad_fn=<MulBackward>)


In [36]:
gradients = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(gradients)
print(x.grad)

tensor([ 51.2000, 512.0000,   0.0512])


In [39]:
print(x.requires_grad)
print((x**2).requires_grad)
with torch.no_grad():
    print((x**2).requires_grad)

True
True
False


In [40]:
# Update the weights of the network, typically using a simple update rule: weight = weight - learning_rate * gradient


In [49]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 5x5 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 5)
        self.conv2 = nn.Conv2d(6, 16, 5)
        # an affine operation: y = Wx + b

        self.fc1 = nn.Linear(16*5*5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
    
    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2,2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
    def num_flat_features(self, x):
        size = x.size()[1:]
        num_Features = 1
        for s in size:
            num_Features *= s
        return num_Features

net = Net()
print(net)

        

Net(
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [59]:
params = list(net.parameters())
print(len(params))
print(params[0].size())# conv1's .weight

10
torch.Size([6, 1, 5, 5])


In [60]:
input = torch.randn(1,1,32,32)
out = net(input)
print(out)

tensor([[ 0.0102, -0.0903, -0.0574, -0.0430,  0.1165,  0.0235, -0.0132,  0.0829,
         -0.0565,  0.0986]], grad_fn=<ThAddmmBackward>)


In [61]:
net.zero_grad()
out.backward(torch.randn(1, 10))
# Zero the gradient buffers of all parameters and backprops with random gradients

In [62]:
output = net(input)
target = torch.randn(10)
target = target.view(1, -1)
criterion = nn.MSELoss()
loss = criterion(output, target)
print(loss)

tensor(1.3109, grad_fn=<MseLossBackward>)


In [63]:
print(loss.grad_fn)  # MSELoss
print(loss.grad_fn.next_functions[0][0])  # Linear
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])  # ReLU


In [64]:
net.zero_grad()
 # zeroes the gradient buffers of all parameters
print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

loss.backward()

print('conv1.bias.grad after backward')
print(net.conv1.bias.grad)


conv1.bias.grad before backward
tensor([0., 0., 0., 0., 0., 0.])
conv1.bias.grad after backward
tensor([-0.0006, -0.0029, -0.0039,  0.0052, -0.0122,  0.0188])


In [65]:
# The simplest update rule used in practice is the Stochastic Gradient Descent (SGD):

# weight = weight - learning_rate * gradient

learning_rate = 0.01
for f in net.parameters():
    f.data.sub_(f.grad.data * learning_rate)

In [67]:
import torch.optim as optim
# create your optimizer
optimizer = optim.SGD(net.parameters(), lr=0.01)
# in your training loop:
optimizer.zero_grad()
output = net(input)
loss = criterion(output, target)
loss.backward()
optimizer.step()
 # Does the update